version: 0.1
phases:
  install:
    commands:
      - echo Entered the Install phase...
      - npm install lambda-deploy-codepipeline-artifact-to-s3-website --save
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-us-east-1-386289756274 --output-template-file cfaTemplate.yaml
artifacts:
  type: zip
  files:
    - cfaTemplate.yaml
  discard-paths: yes


