version: 0.1
phases:
  install:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm install
      - cd $CODEBUILD_SRC_DIR/s3-deployment-custom-resource; npm install
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/build; zip -r ../AuthFunction.zip *
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-us-east-1-386289756274 --output-template-file cfaTemplate.yaml
artifacts:
  type: zip
  files:
    - cfaTemplate.yaml
    - AuthFunction.zip
  discard-paths: yes
