version: 0.1
phases:
  install:
    commands:
      - npm install
      - cd $CODEBUILD_SRC_DIR
      - npm install npm-install-all
      - npm install aws-sdk fs
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR; npm run build
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR/build; zip -r ../package.zip *
      - aws cloudformation package --template-file template.yaml --s3-bucket deploy-nicho9pi-us-east-1 --output-template-file cfaTemplate.yaml
artifacts:
  type: zip
  files:
    - cfaTemplate.yaml
    - package.zip
  discard-paths: yes