version: 0.1
phases:
  install:
    commands:
      - npm install -g mocha
      - npm install
      - npm install aws-sdk
  post_build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket deploy-nicho9pi-us-east-1 --output-template-file cfaTemplate.yaml
      - zip -r app-api.zip .
      - lambda-packager package AuthFunction AuthFunction.zip
artifacts:
  type: zip
  files:
    - cfaTemplate.yaml
    - app-api.zip
    - AuthFunction.zip
