version: 0.1
phases:
  install:
    commands:
      - npm install
      - cd $CODEBUILD_SRC_DIR
      - npm install
  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - node configure.js $STAGE
   build:
      commands:
      - cd $CODEBUILD_SRC_DIR
      - npm run build
      - aws cloudformation package --template-file template.yaml --s3-bucket deploy-nicho9pi-us-east-1 --output-template-file cfaTemplate.yaml
      - zip -r auth.zip .
artifacts:
  type: zip
  files:
    - cfaTemplate.yaml
    - auth.zip
