version: 0.1
phases:
  install:
    commands:
      - npm install
      - cd $CODEBUILD_SRC_DIR
      - npm install
      - aws cloudformation package --template-file template.yaml --s3-bucket deploy-nicho9pi-us-east-1 --output-template-file cfbTemplate.yaml
artifacts:
  type: zip
  files:
    - cfbTemplate.yaml
