AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deployment Auth
Parameters:
  Bucket:
    Type: String
  CodeZipKey:
    Type: String
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri:
        Bucket: !Ref Bucket
        Key: !Ref CodeZipKey
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /Clear0URL
            Method: GET
