AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: s3://deploy-nicho9pi-us-east-1/AuthFunction.zip
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /Clear0URL
            Method: GET
