AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Deployment Auth
Resources:
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /Clear0URL
            Method: GET
